### ISSUE TITLE
add USGS watermark SVG to the package

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#122]
![image](https://cloud.githubusercontent.com/assets/2349007/20893034/f03d1c38-bad5-11e6-8be5-4fa9e5f7df90.png)

for matthew. 

Like the favico, it might be nice to have this in the package (`inst/extdata/` or `sysdata.rda`?) so it is easy to pull in

**Comment by aappling-usgs** [comment]
it's right here for the copying - let's get it into vizlab: https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/fetch.watermark.R

**Comment by jread-usgs** [comment]
It would be nice to be able to add an argument to the fetch that would make it simple to "justify" the watermark - such as baseline alignment/center/top, left, right middle. Otherwise, fiddling is needed.

**Comment by aappling-usgs** [comment]
suggesting jordan as reviewer

**Comment by jzwart** [comment]
So should this live in `inst/images/` and then create function to fetch from folder and align?

**Comment by aappling-usgs** [comment]
Ooh, I think I like that! What I don't know yet personally is how and where the aligning should happen. In Maria, it appears that the alignment happened in [visualize.hurricane_map](https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/visualize/visualize.hurricane_map.R#L43-L52), but @jread-usgs suggested above that we could move this to be an argument to the `fetch()` function...

@jread-usgs, I'd like some more input from you here on why doing the alignment during the fetch would be preferable to doing it during the visualization step. Isn't alignment more of a visualization thing (or even a javascript thing) rather than a fetch thing? Maybe we just need a simpler way of adjusting the alignment in the visualize phase?

**Comment by jread-usgs** [comment]
Good point @aappling-usgs 
*if* we use something like D3 to place the watermark (instead of R) it can be smart and do things like get the height or width of the bounding box for the watermark and use that info to place it correctly w/ justification. 

So yes, I don't think justification is needed in the fetch assuming we use better methods to place the watermark.

**Comment by aappling-usgs** [comment]
Deal - sounds like a good D3 task

**Comment by jread-usgs** [comment]
yes it does :+1:
