### ISSUE TITLE
refine viz.yaml structure

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#14]
consider refinements to make the viz.yaml even more

1. minimal (therefore unlikely to get out of date)
2. complete (sufficient for generating & describing the viz)

i'm starting with viz.yaml in great-lake-microplastics as of 6/8/2016 commit (https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/be448d84faff762617b98cf96972079701e05fec/viz.yaml) as a model.

some specific comments/questions:

1. [`1` `vizlab: "0.1"`](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/be448d84faff762617b98cf96972079701e05fec/viz.yaml#L1): does this describe the vizlab package version? if so, maybe it should be omitted from this file and/or automatically populated in future vizzies?
1. [`7` `path`](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/be448d84faff762617b98cf96972079701e05fec/viz.yaml#L7): the path gets [sent](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/9ef7655811e6c2bbc1d43c7d17c78f9c5192b7c4/scripts/lib/buildPages.R#L11) via whisker.render to [`ga('send', 'pageview', '{{ vizlab-page-path }}');`](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/c41c9fa9318e2d7171af3586c3b1de9471fe25a0/layout/templates/index.mustache#L47). then what does it do? where will a description of `path` and other fields be documented so that a newcomer will know what to enter in the viz.yaml?
1. [`19` `sections: [header, intro, relativeAbundance, environmentalEffects, landUse, footer]`](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/be448d84faff762617b98cf96972079701e05fec/viz.yaml#L19): how does the `sections` list in this line match up with the entries in the following `sections` block? could this list be deleted in favor of just using the names from the `sections` block?
1. [`81-84` `mimetype`,`readParam`, etc.](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/be448d84faff762617b98cf96972079701e05fec/viz.yaml#L81): these lines in the yaml are becoming complex to handle the broad diversity of possible data formats. would be nice to revisit this design decision - could it make more sense to allow users to define a function, or name one of a few vizlab helper functions, rather than setting a possibly long list of arguments to a required vizlab function?
1. [`98` `tags: [mobile, desktop, ie]`](https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/be448d84faff762617b98cf96972079701e05fec/viz.yaml#L98): this line gets repeated for every figure. could it be given as a single line under `figures` rather than a different line under each element of the figure list?

**Comment by jiwalker-usgs** [comment]
I'll try to explain my thinking on these a bit.
1. This is the version of the viz.yaml "spec" so that if we add new features (sections, tags, etc) we can fail more nicely on old yaml files (or maybe be backwards compatible).  I think this will mostly be created by the viz.skeleton that is forthcoming and not needed to be changed, but it is good to version things like this (note: I borrowed this from docker-compose yaml spec).

2. path is meant to describe the name of the url after /vizlab or wherever the final resting place is.  Currently this is handled on the AWS side by putting it into the vizlab/{{path}} key for S3.  I'm thinking we will have a lightweight url rewrite scheme on the server in the future that will be able to handle this.

3. I split this up into pages and sections.  A page is the top level whisker render, and a page contains sections (defined in sections area).  I'm thinking we may have multipage viz where header and footer are shared, but the figure sections are not.

4. I'd like to talk about what is too much in here, but the idea is to bring features in declaratively and bringing in helper functions extensibly.  We should remove params that clutter this up and require custom scripts instead.

5. I think we are going to get rid of tags until we decide we need them.
