### ISSUE TITLE
dynamic hover

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#148]

**Comment by eread-usgs** [comment]
Re-using some SVG JS stuff- make this a part of the package that is re-usable so that we dont have to C/P each time. Also improve function- get Mary on this? Needs more in order to be a robust hover.  Needs cleanup from JS person.

**Comment by eread-usgs** [comment]
HI @mbucknell I think this is the task associated with the work thought you'd bring a lot to- just adding you as an assignee for tracking. This issue still needs more detail, which you can hopefully get from @jiwalker-usgs.

**Comment by aappling-usgs** [comment]
This issue was also referenced as "good JS function for tooltips that we can reuse" in #98

**Comment by jread-usgs** [comment]
I thought @mbucknell did this work. Did it not end up in the package? Also, the interns refined it in their summer work and we could likely borrow from their solution.

**Comment by aappling-usgs** [comment]
Oh, great! I don't know where to look for it - could you point out some of the relevant code?

**Comment by aappling-usgs** [comment]
Found it: https://github.com/USGS-VIZLAB/vizlab/pull/168

**Comment by jread-usgs** [comment]
and https://github.com/USGS-VIZLAB/active-flood-viz/blob/b70fc869fc08f66e3f7506e0803ad3157744c966/floodviz/static/js/tooltip.js @aappling-usgs

**Comment by aappling-usgs** [comment]
Next step on this issue is to look at the interns' work at https://github.com/USGS-VIZLAB/active-flood-viz/blob/master/floodviz/static/js/tooltip.js and https://github.com/USGS-VIZLAB/active-flood-viz/blob/master/floodviz/static/js/map.js, then import innovations from there into https://github.com/USGS-VIZLAB/vizlab/blob/master/inst/js/svg.js

**Comment by jread-usgs** [comment]
Overview of interns' work: 

1. added awareness of the "top" of the svg to the tooltip (was only adjusted for sliding off right and left before)
2. added D3 to the tooltip code which makes the select and modification of the tooltip cleaner
3. parameterized the triangle of the tooltip, so that is adjustable
4. cleaner code and better documentation in general

**Comment by aappling-usgs** [comment]
Mary also mentioned that the current hover functionality wasn't working as of Irma - there may be some bugs or incompatibilities that could be fixed

**Comment by aappling-usgs** [comment]
jake could be a PR reviewer - he's looking for interactivity skills

**Comment by aappling-usgs** [comment]
remaining for this issue after #272 : the improvements the interns made this summer. the challenge is to determine what would be useful to bring in, e.g., making sure tooltips don't get clipped by the stop of the svg.

**Comment by aappling-usgs** [comment]
see if mary can do a PR review on this stuff

**Comment by aappling-usgs** [comment]
closed by #272 and #295. D3 was mentioned above but will be handled in other issues.
