### ISSUE TITLE
Add retina favico

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#222]
retina next to (our) non-retina favico on a retina screen:
![image](https://user-images.githubusercontent.com/2349007/30555744-09a1a8d6-9c6e-11e7-87c7-813d2aac092c.png)

**Comment by ldecicco-USGS** [comment]
Also, looks like the landing page is missing a favico

**Comment by mwernimont** [comment]
Was able to create a favicon that will switch based on what size is needed.  Found you can make a single favicon file with several sizes from https://www.smooster.com/en/blog/how-to-create-a-favicon-for-retina.html using http://www.xiconeditor.com/

All we need to do now is add this line of code to the vizlab landing page.
<link rel="shortcut icon" href="path-of-the-image/favicon.ico" />

Which since I have that issue assigned to me, I'll do.

**Comment by mwernimont** [comment]
https://github.com/USGS-VIZLAB/vizlab/pull/274 @jread-usgs

**Comment by jread-usgs** [comment]
fixed in #274
