### ISSUE TITLE
Visualize - Specify multiple outputs for a single visualization step [5]

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#35]
I originally wanted to punt on this, but I think we are going to continue to run into spots where we need a mobile image to behave differently or be styled differently. I'd like to understand our preferred strategy for doing this (even if we don't implement until later). My guesses:

1) we render svgs inline, and have a different index.html for mobile and one for desktop
2) do an image swap (like we do in Lower CO drought)
3) stick the logic inside the svg (as js) so it mutates when its size changes

**Comment by jiwalker-usgs** [comment]
To chime in here, I would prefer 1, 3, or some mixture of the two.  I think rendering svgs inline will give us a lot more options in dealing with screen sizes.  The general case will let us have a single svg that works both on mobile and desktop, with just some adjustments based on some css rules.  I see it possible though that we may need two completely separate graphics, and in order to handle this we will need to serve up two versions of the page.

I think to handle this we should look to the near/medium term to see what we might need for differences in the pages and build this into what results from the `publish` phase, which is currently the last part of the build.  We can then go about making the dynamic `host` phase which will render the page with the appropriate content from the publishing.  I think we've held off on this in favor of static pages because of uncertainty with the hosting solutions available, but it is probably worth deciding on something and pushing it forward.

**Comment by eread-usgs** [comment]
First step: More planning needed on this b/c we are not sure how to accomplish it.

**Comment by aappling-usgs** [comment]
I think that code like this (from [Maria](https://owi.usgs.gov/vizlab/hurricane-maria/)) is evidence that we have a working solution for this issue:
```
<figure>
   <img class="vizlab-landscape" src="images/hurricane-map-desktop.svg" title="Hurricane Maria's impact on precipitation and river gage height in Puerto Rico" alt="Map of Hurricane Maria's water footprint" />
   <img class="vizlab-portrait" src="images/hurricane-map-mobile.svg" title="Hurricane Maria's impact on precipitation and river gage height in Puerto Rico" alt="Map of Hurricane Maria's water footprint" />
   <figcaption>Puerto Rico and the Virgin Islands</figcaption>
</figure>
```

**Comment by aappling-usgs** [comment]
jordan and marty confirm that we're good on this issue.
