### ISSUE TITLE
Fetch- timestamp [2]

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#40]
Part of fetch. Timestamp function is working for SB, but there is more to be done for timestamping done on local files, URLs, or other methods.

Rather than downloading the file each time, timestamp is inspected and service is checked to determine if there's a change. timestamp.sciencebase function does this for SB. 

Needs to be tested and verified. There are three Fetch functions implemented, for each of those there's a timestamp function that needs to be checked. 

Fetch: File, SB, and URL functions. 

URL needs to be implemented, SB needs to be tested and verified. File needs to be tested.

**Comment by eread-usgs** [comment]
timestamp for file is taken care of. URL timestamp is more complicated. 
code to retrieve timestamp is in place, but nothing is using it. 

- [ ] override for timestamp
- [ ] The logic needs to be put in place to check the timestamp. 
- [ ]  URL timestamp

**Comment by wdwatkins** [comment]
The functions themselves should be good to go in #52, but some other issues:

- For local files, there is some redundancy in checking the timestamp, since `make` already checks the modified tag itself when the data file is listed as a dependency.  Do we want to only use the timestamp as a dependency to avoid this?

- What happens when `fetchTimestamp` is false in the viz.yaml?  It skips the fetch, but what if as in the example viz iris-data there is no processed file cached?  If you wanted to change the visualization step, the fetch would still have to happen.  Should there be 'skip' flags in each section, so that they can be turned off if you want?  

- An example with a local file that gets processed would make the things☝️  easier to test

**Comment by eread-usgs** [comment]
More examples in the Process script would help to show this works. Add another figure to the test viz that accesses something remote. Cuyahoga example.

**Comment by wdwatkins** [comment]
#61 should finish this.  Also made a PR to the example viz repo to add a sciencebase block https://github.com/USGS-VIZLAB/example/pull/7

**Comment by eread-usgs** [comment]
fixed in #61
