### ISSUE TITLE
Publish-export. Separate these. [3]

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#41]
Export and publish are currently related, but export should be it's own step. Currently it is done manually. 

Two parts: 1) export as an option on the viz yaml objects, which means that file will end up in the output. 2) Pull out export so that if you're implementing your own publish, you don't have to take care of the export portion. Right now, publish does both combining and exporting.

**Comment by aappling-usgs** [comment]
1) `export` is an option on each viz.yaml item, though you almost never have to type it because there are defaults (`true` for process, `false` otherwise): https://github.com/USGS-VIZLAB/vizlab/blob/2dc543aeae0bd9f8a4849b8261157a1d5dc87861/inst/viz.defaults.yaml

2) Today, export is still a part of publish. Example: https://github.com/USGS-VIZLAB/vizlab/blob/c642e64162823d2962739c3cd6ee658d10cfc5e9/R/publish.R#L111-L116. So (2) isn't complete.

Regarding the urgency of this issue:
* Note that nobody has pushed for the resolution of this issue in over a year.
* Note that there are 0 publish scripts for hurricanes Maria, Irma, or Matthew, and only 1 for Harvey ([`publish.json()`](https://github.com/USGS-VIZLAB/hurricane-harvey/blob/master/scripts/publish/json.R)), so implementing your own publish doesn't happen all that often. 
* However, I also don't see a call to `export()` in that Harvey function and take this as evidence that `export()` got forgotten and so really ought to be implemented elsewhere so it doesn't get forgotten again. That function was used for this item: https://github.com/USGS-VIZLAB/hurricane-harvey/blob/master/viz.yaml#L349-L354. Rather than adding a call to `export()` within `publish.json()`, someone cleverly hacked in an `export: true` in the corresponding data step for that json file: https://github.com/USGS-VIZLAB/hurricane-harvey/blob/acad75321841d9bcdde8f10ef43cb6fc2f4f87df/viz.yaml#L271-L283. It worked but wasn't optimal and probably took some sleuthing. An alternative solution specific to this one Harvey instance would be to implement a vizlab `publish.json` method.

**Comment by aappling-usgs** [comment]
My take as of 10/3/17 is that it will be simplest and almost as effective to resolve #263 while leaving this issue (#41) unresolved.

**Comment by aappling-usgs** [comment]
Still thinking what I thought in October: makes sense to resolve #263, which I'm doing in #328. That PR also removes the need to specify `export: TRUE`; instead, if you reference any item as a `depends` in a publish item, it'll get exported with no fuss (you could set `export: FALSE` to avoid this, but I don't know why you would) (OK, a little bit of fuss - you do need to specify a mimetype for the exported item. but that's it). 

I don't see publish and export getting separated anytime soon. They're pretty deeply intertwined, and we don't have a strong need for a different approach at this point.
