### ISSUE TITLE
Generated remake.yaml files

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#5]
Much of the remake is boilerplate that can be generated from viz.yaml declarations already made.  Define what can be generated and what should be left to the user.

**Comment by jread-usgs** [comment]
how far does this go? to be decided. At least figs, data, and layout

**Comment by aappling-usgs** [comment]
i will take first stab at this. looks like i don't have permission to adjust Assignees, etc. - @jiwalker-usgs , may i have permission, please?

**Comment by jiwalker-usgs** [comment]
I assigned you, I'll check on permissions.

**Comment by aappling-usgs** [comment]
For discussion (@jiwalker-usgs, @jread-usgs, etc.): 

We're currently building a system where arguments to any function get passed in as named arguments in viz.yaml. For example: 
```
fetch:
  -
    id: Cuyahoga
    location: cache/fetch/CuyahogaTDS.csv
    fetcher: sciencebase
    remoteItemId: 575d839ee4b04f417c2a03fe
    remoteFilename: CuyahogaTDS.csv
    mimeType: text/csv
```
`remoteItemId` and `remoteFilename` are expected by `fetchData.sciencebase` and are accessed as `getContentInfo(viz.id, 'fetch')$remoteItemId`, etc.

This is sort of nice because the arg structure is flat in viz.yaml, and args like `remoteFilename` could also apply to some other functions that might get written in the distant future such as `writeData.sciencebase`. But it gets strange when you start thinking about custom fetchers, processors, and visualizers:
* do these custom functions also get args passed in as named fields in the viz.yaml data item? If so, how do we prevent users from accidentally creating an argument name that overwrites some basic information about the item (e.g., `reader`, `mimeType`, or `export`)? 
* my current implementation passes the entire output of `getContentInfo(viz.id, 'fetch')` to every fetcher implementation by default. This guarantees that any custom arguments will reach the fetcher, but we're also providing more information to custom functions than I think is strictly necessary - for example, _should_ `fetchData.mycustomfetcher` have easy access to `data.info$reader`? It's possible but nontrivial to filter out `reader` and other non-custom fields when all fields are in the same flat list for each item.

Alternatives to having named arguments within the main fields of a viz.yaml data item:

1. Discourage arguments altogether. We've tried some of this already, and often it makes sense and keeps the viz.yaml tidy, but what about the case where someone writes a custom fetcher for, say, Google Drive? Then if they want to fetch more than one file from Drive, they have to write a new fetcher function for each file. But if we allowed arguments they could just change the filename argument and call the same fetcher repeatedly.

2. Put args in their own subblock, e.g., `args`, within the data item. I'm leaning [back] toward this option because I'm persuaded that arguments could indeed be useful, and I want them to be able to have arbitrary names that are guaranteed not to interfere with other built-in functionality for a viz data item. For consistency across all functions, I think this requires moving `remoteItemId`, `remoteFilename`, and `remoteURL` into said `args` subblock. Otherwise we end up treating custom fetchers very differently from built-in fetchers, which seems wrong to me.

Thoughts?

**Comment by jread-usgs** [comment]
This is tricky, and my thoughts on the rules for the viz.yaml were more influenced by the nuances of the visualizers (I hadn't really thought about the different fetchers). On one hand, I like the clean simple rules of `1`, because it is a slippery slope to have a bunch of args that don't have context for people that would be messing around with only the viz.yaml and some templates.

But...this makes it really tricky to make really simple changes to styles and such. My use-case: In these vizzies, we tend to have some theme colors that are used consistently (such as `#1975d1` for water in the low co drought viz, and the different colors for microplastic types). I was asking about moving `args: col:#1975d1` into the viz.yaml so that someone could easily have access to style changes w/o diving into the different `visualize` function. 

That issue is maybe a little separate from your question, as I could also deal with it by making simple style things sit in certain clear places within the visualize functions, or we could have a `styles.yaml` or something that sets these rules (?) that the visualize functions have access to. 

Either way, I could deal with my use case with either your `1` or `2` option, but `2` would make it easier, with the trade-off being the viz.yaml gets more complex. it also seems to make your fetcher easier for the reasons you state above. I am ok w/ that...but are others?

**Comment by aappling-usgs** [comment]
I'm OK with it, and poor @jiwalker-usgs is out of town =). (@jiwalker, if you want us to undo this, it can be done. but i'm sold on option 2 again based on the above thoughts.) trying it out with the above commit & associated PR #25.

**Comment by aappling-usgs** [comment]
still open for
1. @jiwalker-usgs's go-ahead (or not) on nested args, and
2. some sort of remake or make file for the layout, ideally in conjunction with definitions of `getFigureInfo`, `googleAnalyticsId`, `buildPages`, `buildJS`, `runAll`, etc. that are built into vizlab

**Comment by jiwalker-usgs** [comment]
I'm a little bit worried that I might not be so down with the args, but I might just have to change my way of thinking.  I was going towards a more object oriented model (each item in the yaml results in an object) and then have the methods act on said objects.  This goes more towards a functional style where there is more information needed about the function that is getting called and what it requires to call it.  I don't think it is wrong to go in this direction, but I think the dispatching that is being done based on the object oriented way of doing it is probably not needed in this case.

The way that I'm thinking of this is not that we are adding args to the fetcher, visualizer, etc; but that we are adding properties to the object that are available as needed by the methods that are dispatched to.  I'm open to changing my thinking, I just think it is two opposing models.

**Comment by jread-usgs** [comment]
@jiwalker-usgs can you weigh in quick with how 
`remoteItemId: 575d839ee4b04f417c2a03fe` and `remoteFilename: CuyahogaTDS.csv` would be handled then? I am just having trouble thinking about your plan w/o seeing an example.

**Comment by aappling-usgs** [comment]
Yeah, @jiwalker-usgs, you and I talked about this a lot two weeks ago. I think the revealed challenge with the object oriented model is that the objects differ a lot in which fields they need to contain - in effect, every different fetcher, processor, and visualizer requires a different class of object (probably inheriting from some parent object, but quite different anyway). And many of those classes are not known to vizlab because they're custom. This takes away a lot of what I think I remember about the advantages of OO models.

Given the logistical challenges the wally-bass team is facing, and given that I've been doing most of the vizlab development this week, and given that I still prefer the functional style in this case, I'm going to keep pushing for the `args` subblock for at least the duration of the wally-bass viz.

**Comment by aappling-usgs** [comment]
PS - I am still sticking with your OO-consistent way of dispatching functions. It's just that the objects are pretty light - just a viz.id wrapped in a class name - rather than being the more heavyweight multi-field objects you pioneered for the microplastics viz.

**Comment by jiwalker-usgs** [comment]
I am not trying to say OO is the way to go, just that that is how I was thinking of things.  I think the mix of the two styles may be confusing as well.  I'm also not trying to hold things up, as I'm not actually contributing much.
