### ISSUE TITLE
Declare roles and responsibilities

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#6]
Define what these roles are for visualizations and declare on a per viz basis who is fulfilling what roles.

**Comment by jread-usgs** [comment]
how do we make this clear? on the readme?

**Comment by aappling-usgs** [comment]
This has turned out to be fluid from viz to viz, a product of the needs of a viz and the skills of the team members. We have learned that separating tasks to minimize merge conflicts is useful - people should be working on different files. And we have learned that having a complete vizzie to look at right away is useful - we can get and share feedback quicker. But I still don't see a place for a formal solution, so I think we can close this issue and continue to learn by doing.
